[package]
name = "p-lend"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = "0.9.2"
pinocchio-pubkey = "0.3.0"
pinocchio-system = "0.3.0"
bytemuck = { version = "1.23.0", features = ["derive"] }