[package]
name = "p-lend"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = "0.9.2"
pinocchio-pubkey = "0.3.0"
pinocchio-system = "0.3.0"
solana-sdk = "3.0.0"


[dev-dependencies]
litesvm = "0.8.1"
solana-sdk = "3.0.0"
hex = "0.4"
